import { formatMoney } from '../api.js';

function MetricCard({ label, value, hint }) {
  return (
    <article className="metric-card">
      <span>{label}</span>
      <strong>{value}</strong>
      <small>{hint}</small>
    </article>
  );
}

export function AdminPage({
  analytics,
  adminForm,
  onAdminFormChange,
  adminCode,
  onGenerateDiscount,
  error
}) {
  return (
    <>
      <section className="stats-grid" aria-label="Store metrics">
        <MetricCard label="Orders" value={analytics ? analytics.totalOrders : '0'} hint="Completed checkouts" />
        <MetricCard label="Revenue" value={analytics ? formatMoney(analytics.totalRevenue) : '$0.00'} hint="Final totals" />
        <MetricCard label="Discount codes" value={analytics ? analytics.totalDiscountCodes : '0'} hint="Generated by admin" />
        <MetricCard label="Discounts given" value={analytics ? formatMoney(analytics.totalDiscountsGiven) : '$0.00'} hint="Applied at checkout" />
      </section>

      <section className="card admin-panel">
        <div className="section-heading">
          <div>
            <p className="eyebrow">Admin</p>
            <h2>Generate a code</h2>
          </div>
          <p>Use the same API as the backend admin route.</p>
        </div>

        <form className="admin-form" onSubmit={onGenerateDiscount}>
          <label className="field">
            <span>Percentage</span>
            <input
              type="number"
              min="0"
              max="100"
              value={adminForm.percentage}
              onInput={(event) => onAdminFormChange({ ...adminForm, percentage: event.currentTarget.value })}
            />
          </label>

          <label className="field">
            <span>Type</span>
            <select
              value={adminForm.type}
              onChange={(event) => onAdminFormChange({ ...adminForm, type: event.currentTarget.value })}
            >
              <option value="manual">Manual</option>
              <option value="nth_order">Nth order</option>
              <option value="special">Special</option>
            </select>
          </label>

          <label className="field">
            <span>Max usage</span>
            <input
              type="number"
              min="1"
              value={adminForm.maxUsage}
              onInput={(event) => onAdminFormChange({ ...adminForm, maxUsage: event.currentTarget.value })}
              placeholder="Optional"
            />
          </label>

          <label className="field field--wide">
            <span>Expiration</span>
            <input
              type="datetime-local"
              value={adminForm.expiresAt}
              onInput={(event) => onAdminFormChange({ ...adminForm, expiresAt: event.currentTarget.value })}
            />
          </label>

          <button type="submit" className="button button-primary field--wide">
            Generate code
          </button>
        </form>

        {adminCode ? (
          <section className="result-card">
            <p className="eyebrow">Generated code</p>
            <strong>{adminCode.code}</strong>
            <small>
              {adminCode.details.percentage}% {adminCode.details.type} discount
            </small>
          </section>
        ) : null}
      </section>
    </>
  );
}
